version: "3.8"

services:
  ingesta:
    image: synteck428/my-dataproject-ingesta:latest
    environment:
      - SOCRATA_USERNAME
      - SOCRATA_PASSWORD
      - SOCRATA_APP_TOKEN
      - S3_BUCKET_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    networks:
      - my-network
    container_name: ingesta


  model:
    image: synteck428/my-dataproject-model:latest
    networks:
      - my-network
    container_name: modelo


  webapp:
    image: synteck428/my-dataproject-webapp:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - backend-static:/usr/share/nginx/html/backend-static
    networks:
      - my-network
    container_name: webapp


  api:
    image: synteck428/my-dataproject-backend_webapp:latest
    ports:
      - "8000:8000"
    environment:
      - S3_BUCKET_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    networks:
      - my-network
    volumes:
      - backend-static:/usr/share/nginx/html/backend-static
    container_name: api



  api_flask:
    image: synteck428/my-dataproject-backend_webapp:latest
    ports:
      - "7000:5000"
    environment:
      - DATABASE
      - RELATIONAL_DATABASE_HOST
      - USER_DATABASE
      - DATABASE_PASSWORD
      - S3_BUCKET_NAME
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    networks:
      - my-network
    container_name: api_flask




networks:
  my-network:
    driver: bridge
    
volumes:
  backend-static: