version: '3.8'
services:
  webapp:
    image: synteck428/my-dataproject-webapp:latest
    env_file:
      - .env
    ports:
      - "8080:80"

  ingesta:
    image: synteck428/my-dataproject-ingesta:latest
    env_file:
      - .env

  model:
    image: synteck428/my-dataproject-model:latest
    env_file:
      - .env
