version: '3.8'
services:
  webapp:
    image: synteck428/my-dataproject-webapp:latest
    environment:
      - SOCRATA_USERNAME=${SOCRATA_USERNAME}
      - SOCRATA_PASSWORD=${SOCRATA_PASSWORD}
      - SOCRATA_APP_TOKEN=${SOCRATA_APP_TOKEN}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    ports:
      - "8080:80"

  ingesta:
    image: synteck428/my-dataproject-ingesta:latest
    environment:
      - SOCRATA_USERNAME=${SOCRATA_USERNAME}
      - SOCRATA_PASSWORD=${SOCRATA_PASSWORD}
      - SOCRATA_APP_TOKEN=${SOCRATA_APP_TOKEN}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}

  model:
    image: synteck428/my-dataproject-model:latest
    environment:
      - SOCRATA_USERNAME=${SOCRATA_USERNAME}
      - SOCRATA_PASSWORD=${SOCRATA_PASSWORD}
      - SOCRATA_APP_TOKEN=${SOCRATA_APP_TOKEN}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
