# Usamos una imagen base de Python
FROM python:3.9-slim

# Establecemos el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos los archivos locales al contenedor
COPY . /app

# Instalamos las dependencias necesarias
RUN pip install --no-cache-dir -r requirements.txt

# Exponemos el puerto en el que correrá la aplicación Flask
EXPOSE 5000

# Comando para iniciar la aplicación Flask
CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]
