# Usa una imagen base de Python
FROM python:3.10-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo de requisitos al contenedor
COPY scripts/requirements.txt .

# Instalar las dependencias directamente
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto de los scripts al contenedor
COPY scripts/ .

# Configurar el CMD para ejecutar el script
CMD ["python", "/app/ingesta.py"]
