version: "3.8"

services:
  ingesta:
    image: synteck428/my-dataproject-ingesta:latest
    env_file:
      - .env
    networks:
      - my-network

  model:
    image: synteck428/my-dataproject-model:latest
    networks:
      - my-network

  webapp:
    image: synteck428/my-dataproject-webapp:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - my-network

  api:
    image: synteck428/my-dataproject-backend_webapp:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
