# Dockerfile.model

# Usa una imagen base de Python
FROM python:3.10-slim

# Establece el directorio de trabajog
WORKDIR /app

# Copia los archivos necesarios
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto de los archivos de la aplicación
COPY . .

# Comando para ejecutar el script de modelado
CMD ["python", "scripts/run_model_training.py"]
