name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: |
          docker build -t synteck428/my-dataproject-ingesta:latest -f Dockerfile.ingesta .
          docker build -t synteck428/my-dataproject-model:latest -f Dockerfile.model .
          docker build -t synteck428/my-dataproject-webapp:latest -f Dockerfile.webapp .
          docker build -t synteck428/my-dataproject-backend_webapp:latest -f Dockerfile.backend_webapp .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username synteck428 --password-stdin

      - name: Push Docker images
        run: |
          docker push synteck428/my-dataproject-ingesta:latest
          docker push synteck428/my-dataproject-model:latest
          docker push synteck428/my-dataproject-webapp:latest
          docker push synteck428/my-dataproject-backend_webapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Decode SSH Key
        run: echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > key.pem

      - name: Set permissions for SSH key
        run: chmod 600 key.pem

      - name: Clone repository and fetch docker-compose.yml
        run: |
          git clone --depth 1 --branch master git@github.com:jose1645/chicago-inspections-analytics.git
          cp chicago-inspections-analytics/docker-compose.yml .


      - name: Deploy to EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'

            echo "Iniciando servicios con Docker Compose usando variables de entorno..."
            export SOCRATA_USERNAME=${{ secrets.SOCRATA_USERNAME }}
            export SOCRATA_PASSWORD=${{ secrets.SOCRATA_PASSWORD }}
            export SOCRATA_APP_TOKEN=${{ secrets.SOCRATA_APP_TOKEN }}
            export S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

            echo "Descargando docker-compose.yml desde GitHub..."
            curl -o docker-compose.yml "https://raw.githubusercontent.com/jose1645/chicago-inspections-analytics/refs/heads/master/docker-compose.yml?token=GHSAT0AAAAAACY2DAGJUJZIU25YYEDGP3UEZZXZG7A"

            echo "Actualizando imágenes de Docker..."
            docker pull synteck428/my-dataproject-ingesta:latest
            docker pull synteck428/my-dataproject-model:latest
            docker pull synteck428/my-dataproject-webapp:latest
            docker pull synteck428/my-dataproject-backend_webapp:latest

            
            docker-compose down --remove-orphans
            docker-compose up -d

            echo "Limpieza de recursos no utilizados..."
            docker image prune -af
            docker system prune --volumes -f
          EOF
